### ISSUE TITLE
Use `path_prefix` in determining whether files have changed

### ISSUE THREAD

**Issue by nickthegroot** [vercel/terraform-provider-vercel#100]
When using `vercel_deployment` with `vercel_project_directory`, the `path_prefix` isn't used in determining whether files have changed. 

For example, our team uses a tool to scan through our dependencies and create a minimal version with only the files needed. This is then copied/linked to a temporary folder, when is then referenced by `vercel_project_directory`. While the hashes and files are the same, `vercel_deployment` triggers a redeployment everytime.

```
Terraform will perform the following actions:
# vercel_deployment.vercel-deployment_32649483 (vercel-deployment/deployment) must be replaced
-/+ resource "vercel_deployment" "vercel-deployment_32649483" {
              ...
              + "/var/folders/gy/8cy4sb_92y502v8wv5hsjtsm0000gn/T/OfodQm/yarn.lock"   = "1086964~d85fd5726542bfe41e9a838decc69de639cfe0d6"
              - "/var/folders/gy/8cy4sb_92y502v8wv5hsjtsm0000gn/T/d0rTTb/yarn.lock"   = "1086964~d85fd5726542bfe41e9a838decc69de639cfe0d6" -> null
```

**Comment by dglsparsons** [comment]
Hey, that's a good catch and a really unusual edge case. 

You're totally right too - the paths that form the `vercel_project_directory` are always full paths. The unusual combination of having a random tmp directory means the `vercel_project_directory` outputs will change every time. Even factoring in `path_prefix`, I think `path_prefix` would change every time and cause a re-deployment. 

One "fix" would be to determine that once the path prefix is stripped, nothing has changed. However, you would still see the `must be replaced` message, so it only works around the issue. 

I'm unsure how this could be tackled though, as the file paths are (correctly) different each time.

**Comment by dglsparsons** [comment]
I'm closing this, as I don't think it's a feasible option to be able to support this 🙏
