### ISSUE TITLE
Enable "Protection Bypass for Automation"

### ISSUE THREAD

**Issue by igayoso** [vercel/terraform-provider-vercel#103]
There's no way to set up the "Protection Bypass for Automation" using the Terraform provider. Is it part of any roadmap to add it to the provider?

![image](https://user-images.githubusercontent.com/1875941/213703689-6cd4c112-9b4b-4ddd-8a37-f4443121fe41.png)

Thank you

**Comment by dglsparsons** [comment]
Hey @igayoso, thanks for raising this. It's on the roadmap, along with SSO protection. See #86. 

I'll try to get it prioritised soon :)

**Comment by felixmagnus** [comment]
Hey @dglsparsons 👋 

We see that the password protection feature in the meantime is available in the tf provider, however it seems that the setting for "Protection Bypass for Automation" is still missing. Is that correct?

**Comment by felixmagnus** [comment]
Ok, good to know, thanks!
Will that setting be available in the tf provider anytime soon (tm) ? 😄

**Comment by dglsparsons** [comment]
soon (tm).

**Comment by dglsparsons** [comment]
Hi @igayoso and @felixmagnus, I've added support for this in the latest version of the provider [v0.15.0](https://github.com/vercel/terraform-provider-vercel/releases/tag/v0.15.0). 

You can simply set the `protection_bypass_for_automation` field on a project resource (https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project#protection_bypass_for_automation) to enable this. The secret value is found in the [protection_bypass_for_automation_secret field](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project#protection_bypass_for_automation_secret)

**Comment by igayoso** [comment]
Thank you @dglsparsons! We will check it soon and let you know if we find any issues :)
