### ISSUE TITLE
Applying `vercel_deployment` resource fails with 403

### ISSUE THREAD

**Issue by switchnollie** [vercel/terraform-provider-vercel#108]
Can you please increase the consumed REST API endpoint for [vercel_deployment](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/deployment) to v10?

With the current resource, terraform apply fails with a 403. 
However with `v10` (described in your [REST API docs](https://vercel.com/docs/rest-api/endpoints#add-a-domain-to-a-project)) everything works and a 200 is returned.

**Comment by dglsparsons** [comment]
Hi, thanks for raising this. I'll merge the change, check CI is happy with it, and if so, release a new provider version! 🙌

**Comment by dglsparsons** [comment]
This is released now in v0.11.5.  :)
