### ISSUE TITLE
Error: Invalid value provided for vercel_project_environment_variable when using a variable for target

### ISSUE THREAD

**Issue by kenske** [vercel/terraform-provider-vercel#114]
When trying to apply changes to a `vercel_project_environment_variable` resource, I'm getting the following error:

```
│ Error: Invalid value provided
│ 
│   with module.example.vercel_project_environment_variable.foo,
│   on ./vercel.tf line 84, in resource "vercel_project_environment_variable" "foo":
│   84:   target     = [var.vercel_target]
│ 
│ Set item must be one of production, preview, development, got 
```

This breaks for me in version `0.12` and `0.13`, but the same resource declaration works in version `0.11.5`. This issue only occurs when using a variable for the target, literal strings work fine.

**Comment by dglsparsons** [comment]
Hey @kenske, thanks for raising this - it's a good catch. I've spotted a fix and will get it released early next week. 🤞

**Comment by dglsparsons** [comment]
Hey @kenske - this should be fixed in the latest version of the Provider - v0.13.1. Please update and give it another go - and let me know if any further issues crop up!
