### ISSUE TITLE
[Feature Request] Add Ignore Build resource

### ISSUE THREAD

**Issue by FelixWaweru** [vercel/terraform-provider-vercel#116]
It would be awesome to have a resource that lets users configure which git branches they want ignored in Vercel's build process.

It's possible to do this manually, however it would be really cool if this process could be done in the config. I feel like this would really help improve workflows for projects.

**Comment by dglsparsons** [comment]
Hi @FelixWaweru, i'm a bit unsure what you're picturing here. 

Is the `ignore_command` on the `vercel_project` resource not sufficient for you? 

https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project#ignore_command.

**Comment by FelixWaweru** [comment]
Thanks. That's actually what I was looking for!

I must have overlooked it since I searching for something along the lines of `ignore_build` in the docs
