### ISSUE TITLE
Vercel REST API implementation in Go

### ISSUE THREAD

**Issue by thevilledev** [vercel/terraform-provider-vercel#123]
Hey,

Do you have plans for separating the `client` package to a repository of its own? It is currently the most developed Go implementation to interface with the Vercel REST API. Alternatives are [chronark/vercel-go](https://github.com/chronark/vercel-go) (archived in May 2022) or roll your own. I've been developing a [Vault plugin for Vercel](https://github.com/thevilledev/vault-plugin-secrets-vercel) and would much rather use/extend the same API client implementation your Terraform provider does.

Thanks!

**Comment by dglsparsons** [comment]
Hi, thanks for raising this. It's a great question. 

Currently, there are no plans to separate the `client` API wrapper into its own package, as it's very much purpose-built for the terraform provider. 

You can use it directly though if it fits your use case. There may be minor changes over time, but it should maintain all the functionality it currently has.
