### ISSUE TITLE
Add Support for Log Drains

### ISSUE THREAD

**Issue by osdiab** [vercel/terraform-provider-vercel#128]
I didn't see a way to configure log drains via Terraform.

**Comment by nikolaik** [comment]
Also interested in this!

**Comment by dglsparsons** [comment]
Hi @osdiab, this in now released in [v1.7.0](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/log_drain) of the Vercel Terraform Provider. 

Please give it a go and let me know if you encounter any issues. 

Also, note that this is just for the Configurable Log Drains, not for Integrations, which are separate.
