### ISSUE TITLE
Error inconsistent result after apply

### ISSUE THREAD

**Issue by jiri-dxheroes** [vercel/terraform-provider-vercel#138]
I am having problems with the vercel_deployment. Here is the full error message:

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to vercel_deployment.deploy, provider
│ "provider[\"registry.terraform.io/vercel/vercel\"]" produced an unexpected
│ new value: .team_id: was null, but now
│ cty.StringVal(<MY_TEAM_ID>).
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

Funny thing is that the deployment goes through and the project goes live into production, but it cancels my pipeline, which sucks.

I tried rerunning my old pipelines, which used to work, but they now fail too, so I am fairly certain this is not an issue in my code.

I am using this terraform configuration for this:
```
terraform {
  required_providers {
    vercel = {
      source  = "vercel/vercel"
      version = "~> 0.4"
    }
  }
}

provider "vercel" {
  api_token = var.vercel_account_token
  team      = var.vercel_team_id
}
```

**Comment by dglsparsons** [comment]
@jiri-dxheroes thanks for raising this. I suspect it's something I've introduced in the latest version, https://github.com/vercel/terraform-provider-vercel/pull/137. 

Will look into getting it sorted 🙏

**Comment by dglsparsons** [comment]
Hey @jiri-dxheroes, I've tagged up a new release (v0.15.4) that fixes the original cause for the patch release in a different way. It should be released shortly (once CI has run). From testing, this should solve the issue you're seeing. Please let me know if it doesn't though!

**Comment by jiri-dxheroes** [comment]
It works, thank you for the quick fix ❤️
