### ISSUE TITLE
Release 0.15.3 should be a major release, not a patch

### ISSUE THREAD

**Issue by yannispgs** [vercel/terraform-provider-vercel#139]
The latest release 0.15.3 is considered a patch, but it seems like a major change to me. #137 implies the deletion of a field on every single resource managed by Vercel.

`terraform plan` returns a replacement of every resource managed in this workspace with this new release :

<img width="316" alt="image" src="https://github.com/vercel/terraform-provider-vercel/assets/67374171/26df3202-cf96-41fb-a1e8-21e9238173d7">

And the same happens in other workspaces as well :

<img width="342" alt="image" src="https://github.com/vercel/terraform-provider-vercel/assets/67374171/25143774-638d-4e85-bb98-b19247b92012">

**Comment by dglsparsons** [comment]
Hi @yannispgs, it's a bad release. Working on fixing asap. 🙏

**Comment by dglsparsons** [comment]
Hey @yannispgs, I've tagged up a new release (v0.15.4) that fixes the original cause for the patch release in a different way. It should be released shortly (once CI has run). From testing, this should also solve the issue you're seeing. Please let me know if it doesn't though!

**Comment by yannispgs** [comment]
Hi ! Yes no more issue with the 0.15.4 release 😁
