### ISSUE TITLE
vercel_authentication can't be disabled or configured correctly

### ISSUE THREAD

**Issue by neefrehman** [vercel/terraform-provider-vercel#144]
Since https://github.com/vercel/terraform-provider-vercel/pull/143, existing projects are now having `vercel_authentication` added, to line up with the new Vercel defaults for projects. This is sensible, but the attributes available in the provider don't seem to allow for disabling the setting, which we need to do to maintain our existing project's configuration.

No matter how I update things, I am only able to achieve the below outcomes, implying that authentication will always be enabled:

```diff
+ vercel_authentication = {
  + protect_production = (true | false)
}
```

If the field must now be computed, it would be prudent to introduce a way to disable authentication altogether, like the console allows you to do.

The attributes also don't seem to match the potential configuration options available in Vercel, which are more akin to an enum selection, instead of boolean flags (as can be seen on the [changelog screenshot](https://vercel.com/changelog/deployment-protection-is-now-enabled-by-default-for-new-projects)). I wonder if an API like below would more closely align with Vercel:

```hcl
vercel_authentication = {
  enabled         = bool
  protection_type = "standard_protection" | "all_deployments" | "only_preview_deployments"
}
```

**Comment by dglsparsons** [comment]
Hi @neefrehman, thanks for raising this as an issue. There have been quite a few changes recently to how the Vercel Authentication product works, which has left the provider a bit lacking. 

We have some plans in the works to improve the provider support. This will most likely be a breaking change. We're currently thinking along similar lines to yourself for the API. I've no guarantees on a timeline for this landing, but hopefully, it won't be too far away.
