### ISSUE TITLE
Environment variable import instructions incorrect

### ISSUE THREAD

**Issue by MaitreyaBuddha** [vercel/terraform-provider-vercel#147]
On https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project_environment_variable#import

The instruction "variable id can be taken from the network tab on the project page." Is describing a tab that does not exist, or the instructions are ambiguous.

Furthermore, I can't find _anywhere_ to get the IDs for environment variables for import. So I don't know if this import is even possible.

**Comment by MaitreyaBuddha** [comment]
Ok I found something that works to get them. Documentation could be updated.
```
curl -H "Authorization: Bearer $VERCEL_TOKEN" "https://api.vercel.com/v9/projects/$PROJECT_ID/env"
```

**Comment by dglsparsons** [comment]
Hi @MaitreyaBuddha, that's a good catch. I don't think the env variable IDs are exposed anywhere in the Vercel UI, you're right. From memory the instructions are referrering to developer tools, but this isn't clear at all. 

Good find with the `curl` command too. I'll get this added to the documentation 🙏
