### ISSUE TITLE
Add support for Edge Config

### ISSUE THREAD

**Issue by philwolstenholme** [vercel/terraform-provider-vercel#148]
It'd be great to be able to use TF to manage Edge Config, e.g. to create one and supply initial values, to add a JSON schema etc. 

The schema functionality is new so I'm not sure that's available in the REST API yet but the usual CRUD stuff should be: https://vercel.com/docs/rest-api/endpoints#edge-config

**Comment by philwolstenholme** [comment]
Endpoints for managing Edge Config schemas are available now: https://vercel.com/docs/rest-api/endpoints/edge-config#update-edge-config-schema

**Comment by dglsparsons** [comment]
Hi @philwolstenholme, Edge Config support is now released in [v1.5.1](https://github.com/vercel/terraform-provider-vercel/releases/tag/v1.5.1) of the provider. 

[Documentation](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/edge_config). 

I've added support for `edge_config`, `edge_config_token` and `edge_config_schema` resources and data sources. 

Would you also find `edge_config_item` useful? I know you mentioned supplying initial values.

**Comment by LukeSheard** [comment]
Did `edge_config_item` get created. I have a use for it now, but just wanted to be aware if this was already planned. Otherwise would you be happy to accept a contribution?

**Comment by dglsparsons** [comment]
I'm more than happy to accept contributions for `edge_config_item`! It's on my radar but not planned at the moment.

**Comment by LukeSheard** [comment]
@dglsparsons I've done a first cut [here](https://github.com/vercel/terraform-provider-vercel/pull/196). I've not written huge amounts of go in my life, so I've given it a shot. Please let me know!
