### ISSUE TITLE
Can't setup domain for project

### ISSUE THREAD

**Issue by andreyluchianic** [vercel/terraform-provider-vercel#15]
Hello guys, very glad that you finally created your own terraform provider ❤️ 
Trying to set domain for project and getting this error: 
```bash
╷
│ Error: Error adding domain to project
│ 
│   with module.insurance-new.vercel_project_domain.main["texas"],
│   on modules/vercel-official/main.tf line 89, in resource "vercel_project_domain" "main":
│   89: resource "vercel_project_domain" "main" {
│ 
│ Could not add domain guychecker.com to project prj_JJHr9zb7COBo6APdLbemGopOmWwd, unexpected error: not_found - There is no project for "prj_JJHr9zb7COBo6APdLbemGopOmWwd".
```
Tried with your free `x.vercel.app` domain and also tried with one already configured in current Vercel Team even with different setup for nameservers and every time same error.

Terraform code: 
<img width="917" alt="Screenshot 2022-04-13 at 16 20 05" src="https://user-images.githubusercontent.com/88837148/163189261-baf58be9-aa7e-4a64-82e8-6486db5f614a.png">

Vercel Team Settings: 
<img width="1419" alt="Screenshot 2022-04-13 at 16 20 23" src="https://user-images.githubusercontent.com/88837148/163189493-05a290d2-8dd4-4592-a4d3-fdcd28bf6d0a.png">

**Comment by dglsparsons** [comment]
Hey, thanks for submitting this. 

I think this should work. Are you able to share a small reproduction terraform file so I can investigate further?  

Hazarding a guess here though, I think you might be missing a `team_id` field off the `vercel_project_domain` resource (I assume the domain name and project both belong to a specific team?).

**Comment by andreyluchianic** [comment]
@dglsparsons hey you are right, i didn't used `team_id` in `project_domain` resource. I'll try this out in couple of hours and get back with update

**Comment by cungminh2710** [comment]
I have the same issue. the `vercel_project` has already defined team_id, the `vercel_project_domain` should not need to have it defined. 
```
│ Could not add domain dev.gopavel.com to project
│ prj_8RLNXYiOMogJe7Y6qr5aHUfPz4lO, unexpected error: not_found - There is no
│ project for "prj_8RLNXYiOMogJe7Y6qr5aHUfPz4lO".
```

**Comment by cungminh2710** [comment]
Thanks, I will try that out. I suggest it needs to be mentioned in the documentation to prevent confusion. Cheers

**Comment by dglsparsons** [comment]
@cungminh2710 @andreyluchianic I'm closing this as I don't believe it's an ongoing issue. Feel free to re-open if you still encounter this though! :)

**Comment by andreyluchianic** [comment]
with `team_id` everything works fine, gracias @dglsparsons !
