### ISSUE TITLE
Add support for `vercel_shared_environment_variable` data source

### ISSUE THREAD

**Issue by joaquingatica** [vercel/terraform-provider-vercel#152]
When Shared Environment Variables that already exist in the team are needed from a new project, these cannot currently be used as data source, and one has to rely on duplicating it for the new project.

It would come really handy for gradual adoption of the `terraform-provider-vercel` into new projects of teams that have projects created for a while.

**Comment by dglsparsons** [comment]
Hi, thanks for raising this. It shouldn't be too much work to add so I'll try to get it prioritised asap 🙏

**Comment by joaquingatica** [comment]
Thanks for the quick response! Looking forward to using it

**Comment by dglsparsons** [comment]
Hi @joaquingatica, this is now available in v1.2.0 of the provider. 

Please let me know if you've any feedback!

**Comment by joaquingatica** [comment]
This is great, thanks! I'll test it out soon and let you know if anything.
