### ISSUE TITLE
Cannot update sensitive environment variables

### ISSUE THREAD

**Issue by dprothero** [vercel/terraform-provider-vercel#154]
When you try to change the value of a sensitive environment variable, it fails.

![image](https://github.com/vercel/terraform-provider-vercel/assets/1897006/dcc5ed4a-c191-47fb-b9cb-e73c318295da)

The provider should do a replacement if the underlying API doesn't allow updating.

We have to be able to update the variable, how else do you rotate secrets?

Workaround is to manually delete the secret in the Vercel dashboard before planning/applying.

**Comment by dglsparsons** [comment]
Hi @dprothero, 

Thanks for raising this. To be clear, are you updating the `key` field, or just the value here? I'm surprised to see this fail and it does indeed sound like a bug!

**Comment by dglsparsons** [comment]
Update: never mind, it was quite easy to reproduce. Fix incoming.

**Comment by dglsparsons** [comment]
This is fixed in release v1.2.1. Enjoy :)
