### ISSUE TITLE
Please add "comment" field for DNS records

### ISSUE THREAD

**Issue by dprothero** [vercel/terraform-provider-vercel#156]
Right now, you can't manage the comment field of a DNS record using the provider.

**Comment by dglsparsons** [comment]
Hi @dprothero, thanks for raising this. Looks like the field was added after the initial terraform provider support so I missed adding it. I'll work on getting this added now! 🙏

**Comment by dprothero** [comment]
Hi @dglsparsons I don't think it's working, I'm getting the following trying to apply a plan:

```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.forwardemail_dns.vercel_dns_record.fwd_email_mx2["prothero.com"],
│ provider "module.forwardemail_dns.provider[\"registry.terraform.io/vercel/vercel\"]" produced an
│ unexpected new value: .comment: was cty.StringVal("Terraformed:
│ infrastructure/modules/forwardemail_dns/dns.tf"), but now cty.StringVal("").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by dglsparsons** [comment]
Okay, so digging a bit deeper - it seems like the API has some issue that no other field can be updated at the same time as the `ttl` or `comment`. So, if your plan has changes other than just the 'comment', that could be it. 

I'll look into getting the `api` fixed.

**Comment by dprothero** [comment]
@dglsparsons I've only changed the comment on the record, but the plan shows:

```
  # module.forwardemail_dns.vercel_dns_record.fwd_email_txt["prothero.com"] will be updated in-place
  ~ resource "vercel_dns_record" "fwd_email_txt" {
      + comment = "Terraformed: infrastructure/modules/forwardemail_dns/dns.tf"
      ~ id      = "rec_677648a9a918d22766cd3c11" -> (known after apply)
      + team_id = (known after apply)
        # (4 unchanged attributes hidden)
    }
```

**Comment by dglsparsons** [comment]
Hi @dprothero, this was an API issue and should be resolved now with no changes on the terraform side. 

Let me know if it still doesn't work though 🙏

**Comment by dprothero** [comment]
Works!
