### ISSUE TITLE
[New Resource]: Firewall Rules

### ISSUE THREAD

**Issue by rpf3** [vercel/terraform-provider-vercel#194]
With the [release](https://vercel.com/blog/introducing-the-vercel-waf) of the Vercel WAF, it would be great to be able to configure firewall rules with Terraform.

**Comment by dglsparsons** [comment]
Hi, this should be released now! 

See https://vercel.com/changelog/vercel-terraform-provider-now-supports-vercel-firewall or the [terraform documentation](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/firewall_config) for info.
