### ISSUE TITLE
Add Function Max Duration

### ISSUE THREAD

**Issue by jonpulsifer** [vercel/terraform-provider-vercel#197]
It would be great to be able to programatically configure the function max duration. `15s` is a fine duration, but to have it configurable per project with our own default would be great.

This would help us reduce clickops and adhere more easily to change management policies.

<img width="525" alt="image" src="https://github.com/user-attachments/assets/f56d4569-7d1a-4685-9737-cc765dac410f">

**Comment by dglsparsons** [comment]
Hi @jonpulsifer, thanks for the suggestion - this is a great idea. It was only recently added as a setting. I'll get it sorted 🙏

**Comment by dglsparsons** [comment]
For transparency, we are currently making some behind-the-scenes changes to make this possible. :)

**Comment by smaeda-ks** [comment]
This is now supported https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project#nestedatt--resource_config
