### ISSUE TITLE
Add support for Vercel Secrets

### ISSUE THREAD

**Issue by srgustafson8** [vercel/terraform-provider-vercel#201]
Vercel API has support for creating and managing secrets - [see here](https://vercel.com/docs/rest-api/endpoints/secrets#create-a-new-secret), it would be great to be able to manage these programatically.

**Comment by dglsparsons** [comment]
Hi, these are a sunset feature of the platform. Instead, sensitive [environment variables](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project_environment_variable) should be used, or [shared sensitive environment variables](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/shared_environment_variable) if this is to be used across multiple projects within a team. (note the `sensitive` field on these resources). 

https://vercel.com/changelog/legacy-environment-variable-secrets-are-being-sunset
