### ISSUE TITLE
Project Function CPU Returning Not Found

### ISSUE THREAD

**Issue by aarondunphy** [vercel/terraform-provider-vercel#204]
We are trying to use the following resource: https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project_function_cpu

We added this on Monday 9th September and it worked fine. However since then our Terraform plans have been erroring due to: `{"error":{"code":"not_found","message":"Not Found"}}`.

After some debugging we noticed [here](https://github.com/vercel/terraform-provider-vercel/blob/main/vercel/resource_project_function_cpu.go#L146) that if it returns not found it is removed from our Terraform state.

We're not sure why this returning a 404 and some testing locally with the endpoint results in the same thing. Curl example:
```bash
curl -H "Authorization: Bearer <TOKEN>" "https://api.vercel.com/v1/projects/<PROJECT_ID>/resource-config?teamId=<TEAM_ID>"
```  

Is this an authentication issue or has the endpoint changed? We've even tried with a token from an owner on Vercel and no luck.

**Comment by smaeda-ks** [comment]
@aarondunphy sorry for the trouble. The endpoint was being deprecated recently, and we haven't updated our TF provider yet. We're going to cut a new release with the fix, but meanwhile, you should be able to unblock this by removing the `vercel_project_function_cpu` resource. The current CPU setting should remain unchanged in the subsequent runs even after deleting the resource.

**Comment by aarondunphy** [comment]
@smaeda-ks thanks for the update - is there no plans to allow us to control this through Terraform now?

**Comment by matthewmi** [comment]
> > @smaeda-ks thanks for the update - is there no plans to allow us to control this through Terraform now?
> 
> You will be able to control it through the existing project resource. In lieu of that, `vercel_project_function_cpu` will be retired.

The current documentation seems to be out of date as `vercel_project_function_cpu` is not listed as deprecated yet and CPU isnt listed as a thing in the `vercel_project` https://registry.terraform.io/providers/vercel/vercel/latest/docs/data-sources/project_function_cpu

Is it possible to set the CPU in the vercel_project yet or is that coming in an update?

**Comment by smaeda-ks** [comment]
> Is it currently possible to set the CPU in the vercel_project or is that coming in an update?
It will be included in the next release

**Comment by smaeda-ks** [comment]
@aarondunphy @matthewmi 
Please use the new `resource_config` attribute in the `vercel_project` resource:
https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project#nestedatt--resource_config

We're sorry for the trouble.
