### ISSUE TITLE
Support comments for vercel_project_environment_variable

### ISSUE THREAD

**Issue by zchenyu** [vercel/terraform-provider-vercel#208]
For this feature in the UI:

![image](https://github.com/user-attachments/assets/8a0788e4-b0d7-4076-9023-73778f32420b)

**Comment by dglsparsons** [comment]
Hi, I'm adding support for this in v2.1.0 of the terraform provider. Please upgrade and let me know if you find any issues 🙏

**Comment by zchenyu** [comment]
Thank you!!
