### ISSUE TITLE
Request: Automatic Handling of Rate Limits for Project Environment Variables

### ISSUE THREAD

**Issue by agitelzon** [vercel/terraform-provider-vercel#231]
In my Vercel account, I manage multiple projects across a small number of code bases to represent different environments (e.g., dev, staging, prod) for the same code base. Each project has between 10 and 30 environment variables, totaling 655 `vercel_project_environment_variable` resources managed by my terraform code.

Every time I run a `terraform plan` or  `terraform apply`, I encounter the following rate-limit error, which stops processing:
```bash

│ Error: Error reading project environment variable
│
│   with vercel_project_environment_variable.env_variable["REDACTED"],
│   on main.tf line 66, in resource "vercel_project_environment_variable" "REDACTED":
│   66: resource "vercel_project_environment_variable" "REDACTED" {
│
│ Could not get project environment variable REDACTED prj_REDACTED team_REDACTED, unexpected error: rate_limited - Too many requests - try again in -149 ms (more than 500, code: "api-projects-environment-variable-get").
```
According to Vercel's [rate limit documentation](https://vercel.com/docs/concepts/limits/overview#rate-limits:~:text=Project%20environment%20variable%20retrieval%20per%20minute.), the limit for project environment variable retrieval is 500 requests per minute. Since I have 655 environment variables, I hit this limit every time Terraform I run a plan or apply.

### Current Workaround

Using `terraform apply -parallelism=3` avoids the rate-limit error by limiting the request rate. However, this workaround:

- Slows down the overall execution.
- Is inconvenient to remember and specify each time.

In comparison, providers such as AWS handle this gracefully, even with over 1,000 resources, without manual intervention.

### Feature Request

Could the vercel provider automatically handle rate-limiting to improve reliability and ease of use? 
Potential solutions include:

- Automatic Throttling: Detect when requests are nearing the rate limit and throttle accordingly.
- Adaptive Retry/Sleep Mechanism: Sleep for the number of seconds specified in the error response when a rate-limit error occurs.

Implementing anything, such as one of these options, would allow Terraform users to more efficiently manage larger sets of environment variables in Vercel projects.

Thanks for considering this improvement!

**Comment by agitelzon** [comment]
Here is some sample code to create 550 variables.

```terraform
# Provider configuration
provider "vercel" {
  api_token = var.vercel_api_token
}

# Define the Vercel project
resource "vercel_project" "my_project" {
  name = "my-vercel-project"
}

# Define the number of variables
variable "num_variables" {
  default = 550
}

# Create 550 environment variables using count
resource "vercel_project_environment_variable" "env_var" {
  count      = var.num_variables
  project_id = vercel_project.my_project.id
  key        = "VAR_${count.index + 1}"
  value      = "value_${count.index + 1}"
  target     = ["production", "preview", "development"]
}
```

**Comment by dglsparsons** [comment]
Hi @agitelzon, thanks for raising this. We already have the adaptive sleep/retry mechanism in place. However, it's clearly insufficient here. I'm planning on adding a resource for 
`vercel_project_environment_variables` that will allow setting many env vars in one place, allowing the bulk APIs to be used. 

Would this work for you? 
Something along the lines of: 
```
resource "vercel_project_environment_variables" "env_vars" {
  project_id = vercel_project.my_project.id
  variables  = [ 
     {
        key        = "VAR_${count.index + 1}"
        value      = "value_${count.index + 1}"
        target     = ["production", "preview", "development"]
     }, 
     { 
        key = "foo"
        value = "bar" 
        target = ["production", "preview", "development"]
     } 
}
```

**Comment by agitelzon** [comment]
That might work. Currently, we use a `for_each` to create each `vercel_project_environment_variable`. 

I think I could convert my current object that is used by the `for_each` into a list of this format for each project. 

I wonder if converting to this format will work with `moved` blocks or will I need to have terraform delete the previous variable resources and recreate them with this one.

**Comment by dglsparsons** [comment]
I don't think moved blocks could help you here, so you'd have to delete and recreate them, but hey, that's what IaC is for...

**Comment by dglsparsons** [comment]
Hi, i've added a `vercel_project_environment_variables` resource that uses batch APIs in v2.3.0 of the terraform provider. Please upgrade, give it a go and let me know if you have any more issues! 

https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project_environment_variables
