### ISSUE TITLE
Does terraform-provider-vercel use semver?

### ISSUE THREAD

**Issue by matijs** [vercel/terraform-provider-vercel#234]
The release notes for version 2.0.0 do not mention why there was a major version bump. Were there any breaking changes and if so, what should be done to address these?

**Comment by dglsparsons** [comment]
Hi @matijs, it is semver, although you are right about the release notes. 

The only breaking change was the removal of a deprecated resource - `vercel_project_function_cpu`. 

This can now be configured via the `resource_config` property on the `vercel_project` resource instead. 

https://registry.terraform.io/providers/vercel/vercel/2.2.0/docs/resources/project#nested-schema-for-resource_config
