### ISSUE TITLE
vercel/validator's unit test

### ISSUE THREAD

**Issue by DiegoDev2** [vercel/terraform-provider-vercel#251]
I have a question, don't validators need unit tests? because almost everyone has it. I mean these: https://github.com/vercel/terraform-provider-vercel/blob/main/vercel/validator_automation_bypass_secret.go , https://github.com/vercel/terraform-provider-vercel/blob/main/vercel/validator_framework.go ... etc.

**Comment by dglsparsons** [comment]
Hi @DiegoDev2, they don't _need_ unit tests, no. But they can be quite trivially testable pieces of code.
