### ISSUE TITLE
Feature Request - Git Integration Ignore Build Step

### ISSUE THREAD

**Issue by andreyluchianic** [vercel/terraform-provider-vercel#28]
hello guys,
how about small and very useful feature for monorepos ??
in my case i want to add project in monorepo that has 25 frontends in Vercel and would be pain to manually add this ignore step

https://vercel.com/docs/concepts/projects/overview#ignored-build-step

**Comment by dglsparsons** [comment]
Great suggestion. It looks like the UI input sets a property on a project via the general 'project update' endpoint. 

Sadly the create-project endpoint doesn't currently allow it to be set when creating a project. I'll see if that could be changed though (I guess the current behaviour makes sense in the context of the Vercel UI). 

It's also worth noting that the same field can also be specified on a per-deployment basis, so we'd probably want to support it in a couple of different places.
