### ISSUE TITLE
Feature Request - Node Version

### ISSUE THREAD

**Issue by cungminh2710** [vercel/terraform-provider-vercel#30]
Hi team, it would be useful to control the node version configuration in Terraform. I just upgraded my project to V16, and would love to have the config in code

**Comment by dglsparsons** [comment]
Great suggestion. It looks like the UI input sets a property on a project via the general 'project update' endpoint.

Sadly the create-project endpoint doesn't currently allow it to be set when creating a project. I'll see if that could be changed though as it would make the provider a bit easier to write.

I need to investigate similarly for #28, so I can take a look at both at the same time.

**Comment by cungminh2710** [comment]
Awesome. Not an urgent request. I really appreciate your response, and would love to have #28 too.

**Comment by dglsparsons** [comment]
Hey @cungminh2710. Follow up on this one. Going forwards I don't think this is something we'll support in the terraform provider. 
I don't think it's a setting that Terraform will need, as it's possible to control via a `package.json` file. 

Specifically: 
> Defining the node property inside [engines](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) of a package.json file will override the selection made in the Project Settings and print a Build Step warning if the version does not match. Please avoid greater than ranges, such as >14.x or >=14, because this will match semver major versions of Node.js once available which contains breaking changes.

From [here](https://vercel.com/docs/runtimes#official-runtimes/how-do-i-return-an-error/node-js-version).

**Comment by dglsparsons** [comment]
This is now released in v2.14 of the TF provider. Please update, and let me know if you encounter any issues. Documentation can be found [here](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project#node_version-1).

**Comment by cungminh2710** [comment]
oh lovely thanks! @dglsparsons
