### ISSUE TITLE
NS Domain Record not supported

### ISSUE THREAD

**Issue by DaleLJefferson** [vercel/terraform-provider-vercel#43]
I was able to import a NS record but when I try to run plan I get the following error.

```Item must be one of MX SRV TXT A AAAA ALIAS CAA CNAME, got: NS```

```tf
resource "vercel_dns_record" "domainkey" {
  domain  = "b2b.store"
  name    = "e7a7dafdhajdhd"
  type    = "NS"
  ttl     = 60
  value   = "ns.vali.email."
  team_id = "team_d7ahdhah"
}
```

**Comment by dglsparsons** [comment]
Hey, thanks for raising this. I don't think I added support for `NS` records yet. I'll have a look soon though, as I think it should be fairly simple to add.

**Comment by dglsparsons** [comment]
I'm super happy that it's working out really nicely for you. That is indeed the offending line, although tests/etc. also required. I'll start working on a fix now :)

**Comment by DaleLJefferson** [comment]
I've just tested it and I can confirm it's fixed. Nice work, very impressive turnaround. 🤩
