### ISSUE TITLE
Error: Error adding domain to project

### ISSUE THREAD

**Issue by taylorsteiger-rad** [vercel/terraform-provider-vercel#60]
# Issue 1 #

According to the Provider Docs, the `team_id` is an [optional field](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project_domain#team_id) for the `vercel_project_domain` resource. However, not including the field results in a mismatch with used `team_id`s. The Provider attempts to use your personal `team_id` instead of the `team_id` associated with the `vercel_project_domain`'s `vercel_project`.

Screenshot:
<img width="1289" alt="Screen Shot 2022-08-24 at 10 58 26" src="https://user-images.githubusercontent.com/76705912/186489947-e3856bc2-c2e9-4402-8ebc-70cb41415fcd.png">

Code for `vercel_project_domain`:
```
resource "vercel_project" "ecom-storefront" {
  name      = "ecom-storefront-1"
  framework = "nextjs"
  git_repository = {
    type = "github"
    repo = "a-github-repo"
  }
  team_id                    = "a-team-id"
  serverless_function_region = "iad1"
  install_command            = "npm install -g npm-cli-login && npm-cli-login && npm install"
  public_source              = false
  environment = []
}

resource "vercel_project_domain" "production-domain" {
  project_id = vercel_project.ecom-storefront.id
  domain     = "ecom-storefront-1.vercel.app"
}

# Define the staging domain (pre-production testing)
resource "vercel_project_domain" "staging-domain" {
  project_id = vercel_project.ecom-storefront.id
  domain     = "ecom-storefront-staging-1.vercel.app"
  git_branch = "dev"
}
```

Steps Taken to Debug:

1. Verify `terraform fmt -check`
2. Verify `terraform validate`
3. Verify latest Provider version (using ~> 0.7.1)

Details from `terraform version`:
```
Terraform v1.2.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.27.0
+ provider registry.terraform.io/vercel/vercel v0.7.1
```

# Issue 2 #

Ideally, `vercel_project_domain` resources should be able to be specified, even if they are implied Vercel defaults. Adding a `vercel_project_domain` that has a `domain` that matches its associated `vercel_project.name` triggers an error that the domain already belongs to a "different project", even though the error's "project_id" matches the desired `vercel_project`.

Screenshot:
<img width="1100" alt="Screen Shot 2022-08-24 at 11 12 14" src="https://user-images.githubusercontent.com/76705912/186492469-893ceed0-e627-4cb4-b93a-28e8d505e245.png">

Code for `vercel_project_domain`:
```
resource "vercel_project" "ecom-storefront" {
  name      = "ecom-storefront-1"
  framework = "nextjs"
  git_repository = {
    type = "github"
    repo = "a-github-repo"
  }
  team_id                    = "a-team-id"
  serverless_function_region = "iad1"
  install_command            = "npm install -g npm-cli-login && npm-cli-login && npm install"
  public_source              = false
  environment = []
}

resource "vercel_project_domain" "production-domain" {
  project_id = vercel_project.ecom-storefront.id
  team_id    = "a-team-id"
  domain     = "ecom-storefront-1.vercel.app"
}
```

Steps Taken to Debug:

1. Verify `terraform fmt -check`
2. Verify `terraform validate`
3. Verify latest Provider version (using ~> 0.7.1)

Details from `terraform version`:
```
Terraform v1.2.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.27.0
+ provider registry.terraform.io/vercel/vercel v0.7.1
```

**Comment by dglsparsons** [comment]
Hey @taylorsteiger-rad, thanks for raising this. 

### Issue 1 

I totally see your point about the mismatching `team_id`s being a confusing behaviour. While it's technically optional (because you could omit from _both_ the project, and project_domain), they are always expected to match. It's not sufficient to say that the project_domain knows about the project, because they are standalone resources. 

The fix for your use case is to specify the `team_id` on both resources. 

One thing I've been considering, but haven't implemented yet, is the ability to configure the provider to act on a specific team (akin to how you can configure an AWS provider with a specific region). e.g. 
```terraform 
provider "vercel" {
   team_id = "a-team-id"
}

# All resources will be created underneath "a-team-id" 
# even though they do not specify the team_id. 
resource "vercel_project" "ecom-storefront" {
  name      = "ecom-storefront-1"
  framework = "nextjs"
  git_repository = {
    type = "github"
    repo = "a-github-repo"
  }
  install_command = "npm install -g npm-cli-login && npm-cli-login && npm install"
}

resource "vercel_project_domain" "production-domain" {
  project_id = vercel_project.ecom-storefront.id
  domain     = "ecom-storefront-1.vercel.app"
}
```

Would that help/alleviate your use-case? 

### Issue 2 

You could use the `import` behaviour if you wished to manage those domains through terraform. This is documented [here](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/dns_record#import). 

Saying this, I'm unsure how this would behave if you tried to delete or update the vercel-created project domains.

**Comment by taylorsteiger-rad** [comment]
Hey @dglsparsons,

Thanks for the response and details.

Issue 1: Yep, I was able to get it work by adding the `team_id`. Maybe an update to the docs would be helpful then?

Issue 2: Did you mean to point to the `vercel_dns_record` docs? Seems like that would be separate, but I could be wrong since I have had to mess with DNS records in Vercel yet. The update/delete of the Vercel domain is my primary concern since it seems like it should be possible to manage them in Terraform. We will likely leave the domain out temporarily, and when we plan on launching to our customers, we will add our "production" domain to the Terraform file.

**Comment by dglsparsons** [comment]
Hey @taylorsteiger-rad. I'm glad you were able to resolve your issues here :) 

Absolutely agreed on the documentation - It's definitely something that causes some confusion. 

For 2. I didn't mean to link `vercel_dns_record` 🙈. That should have been a link to the [project domain import](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project_domain#import) - sorry about that. I think adding the production domain to Terraform would make perfect sense though, and is exactly what the resource was intended for :).

**Comment by taylorsteiger-rad** [comment]
Hey @dglsparsons! Thanks for clarifying and being so helpful :)
