### ISSUE TITLE
PNG images in the public folder become corrupt when uploaded via provider

### ISSUE THREAD

**Issue by Tom-Br** [vercel/terraform-provider-vercel#61]
Hi, 

PNG images in the public folder are being corrupted during an upload via the Terraform provider. 
They are not visible in the Vercel console, and do not render properly in the browser either.

Steps to reproduce:
- Add png to public folder
- Deploy to Vercel via Terraform.

See image of faulty png in the Vercel console.
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/14942821/186653385-e03a4213-d260-4f43-af50-c8373f512e05.png">

Kind regards, Tom

**Comment by dglsparsons** [comment]
Hey @Tom-Br, thanks for raising this. Looks like it's due to some line-ending shenanigans. I'll get a fix out ASAP :) .

**Comment by dglsparsons** [comment]
Hey @Tom-Br, this should be fixed as of [v0.8.0](https://github.com/vercel/terraform-provider-vercel/releases/tag/v0.8.0). Could you give it a try and see if the issue persists? Thanks :)

**Comment by Tom-Br** [comment]
Just got around to trying this, it works like a charm.
