### ISSUE TITLE
Question: Is the plan to have support for prebuilt projects deployed?

### ISSUE THREAD

**Issue by palmithor** [vercel/terraform-provider-vercel#65]
The vercel cli supports deploying prebuilt code (see https://vercel.com/guides/deploying-locally-built-nextjs)

When following GitOps it is common to produce an artifact as part of the application pipeline and then deploy this artifact in the  configuration repo. 

It'd be awesome to be able to deploy prebuilt project with the terraform provider.

**Comment by dglsparsons** [comment]
Hey @palmithor, that's a really good question. It's actually something we're actively working on at the moment and I'm hoping to land and release it some time next week. 

I'll let you know as soon as it's available :)

**Comment by palmithor** [comment]
@dglsparsons awesome news, looking forward to hearing from you 🙌

**Comment by dglsparsons** [comment]
Hey @palmithor - This is now released as part of the [v0.9.0 provider changes](https://registry.terraform.io/providers/vercel/vercel/latest/docs/data-sources/prebuilt_project). Enjoy, and let me know if you find any issues 🙌
