### ISSUE TITLE
Proposal: support `team` as a provider configuration argument

### ISSUE THREAD

**Issue by dglsparsons** [vercel/terraform-provider-vercel#70]
Hi, I'm raising this here as I'd like to see if people would find this valuable

# Problem 

Currently, you have to pass `team_id` to every single resource. This is cumbersome but also leads to an easy-to-make mistake in omitting the `team_id` field on a resource. Sometimes the errors can be hard to track down (i.e. project not existing). 

## Proposal 

In the same vein as AWS allowing a 'default' region to be specified for the `aws` provider, it would be nice to allow a team to be configured at the provider level. 

## This could look like the following: 

```terraform
provider "vercel" {
  team = "my-team" // team slug
}
```

and/or potentially 

```terraform
provider "vercel" {
  team = "team_1234abc" // team ID
}
```

I think in both of these cases we should be able to hook into the providers configure method to look up the ID of a team as a one-time operation. We can then reliably use a `team_id` from the provider, unless it is explicitly declared for a resource. This would form a preference hierarchy, with configuration on a resource being the most specific, then the provider configuration. 

## Usage 
 
```terraform
provider "vercel" {
  team = "my-team"
}

resource "vercel_project" "foo" {
   name = "foo" // This would be created on team my-team
}

resource "vercel_project" "bar" {
   name = "bar" 
   team_id = "team_1234abc" // this would be created on team team_1234abc
}

provider "vercel" {
   alias = "no-team" 
}

resource "vercel_project" "qux" {
  name = "qux" 
  provider = vercel.no-team // this would be created on a personal account
}
```

**Comment by viki53** [comment]
Yes please!

Using the slug would be even better, as this could be taken from an existing `project_name` (or similar) variable that's already used in other runs. This would mean one less redundant variable to define 🙏

**Comment by dglsparsons** [comment]
Hi @viki53 and anyone else looking here. 

It is now possible (as of [v0.10.0](https://registry.terraform.io/providers/vercel/vercel/latest/docs#optional)) to configure the team using either a slug or team ID via the `team` field on the `provider` (as per the above issue description). 

Please give it a go and let me know if you encounter anything odd! 🎊

**Comment by viki53** [comment]
Works great! Thank you! 🙌
