### ISSUE TITLE
[feature] vercel_deployment data source

### ISSUE THREAD

**Issue by viki53** [vercel/terraform-provider-vercel#74]
Hi,

I have started moving my team's existing (created by hand before my arrival for the most part) infra to Terraform recently and am encountering a blockage due to some missing data sources in this provider.

For context, I would like to manage some `CNAME` DNS records (directly on Cloudflare — or maybe some other provider in the future —, to avoid having to manage them on Vercel) during a dedicated run but can't seem to find a way to retrieve the generated domains assigned to various deployments (`staging`/`development` and `production` in this case) using data sources.

Note: I am already using `vercel_deployment` resources to create those deployments, but in a different run that only manages the Vercel resource. Hence the need for a data source to retrieve the info in this new run.

Is there a way to get the domain for specific deployments (ideally using a `git_branch` param or something like this) currently or would that be by creating this data source?

**Comment by dglsparsons** [comment]
Hi @viki53, thanks for raising this. 

I think this should be possible already using [this guide](https://vercel.com/guides/using-cloudflare-with-vercel). 

As long as your domain has an A record pointing to `76.76.21.21` and a CNAME with value `cname.vercel-dns.com`, you should be able to use the domain with Vercel (even keeping the Cloudflare nameservers), and you can still manage your DNS records in Cloudflare.

If those two records are present, you should be able to use the Vercel [project domain](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project_domain) resource. 

By the sounds of your use-case, associating a [git_branch](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project_domain#git_branch) with the Project Domain should be what you are after? 

If this isn't sufficient, I can start looking at a Deployment data-source.

**Comment by viki53** [comment]
That is our current setup, yes. but I'm actually wanting to use a different one after we discovered that the way you manage those domains means we can have different two different builds for our production branch.

For more context, last week for example we had a live demo on our production custom domain (linked to our `main` branch), and we got a 404 error on a URL that worked just fine on the generated Vercel domain (also linked to our `main` branch). 

As you can imagine, this isn't very safe for production environments, so I'd like to use a `CNAME` on our side that points directly to the generated domain, without having to use your DNS server. That way we can make sure there's only one production build accessible at any time.

**Comment by dglsparsons** [comment]
Ahh gotcha. I'll look to add a `deployment` data source for your use case. Can't promise any timeline for when it will land though as I think it's fairly low priority so far.

**Comment by dglsparsons** [comment]
For documentation sake, although i'm sure you're aware - this has been released in [v1.8.0](https://github.com/vercel/terraform-provider-vercel/releases/tag/v1.8.0) of the provider. 

Documentation can be found [here](https://registry.terraform.io/providers/vercel/vercel/latest/docs/data-sources/deployment). 

Let me know if there's any problems, or anything else you'd like to see.
