### ISSUE TITLE
vercel_deployment does not deploy preview if production = false

### ISSUE THREAD

**Issue by typytypytypy** [vercel/terraform-provider-vercel#82]
Hi, I am trying to make a preview deployment in terraform, but every time it makes a production deployment

```
resource "vercel_project" "projname" {
  name      = "projname"
  framework = "remix"
  team_id   = "team_id"

  git_repository = {
    type = "github"
    repo = "${github_repository.projname.full_name}"
  }
}

resource "vercel_deployment" "projname_preview" {
  project_id        = vercel_project.projname.id
  team_id           = "team_id"
  ref               = "preview"
  production        = false
  delete_on_destroy = true

  environment = {
    for tuple in regexall("(.*?)=(.*)", file("./.env.prod")) : tuple[0] => tuple[1]
  }
}

```

I would expect when I apply this that the preview branch is deployed to a preview deployment, but my production deployment gets updated.  Do I have something wrong in the syntax?

**Comment by dglsparsons** [comment]
Closing this as it looks stale! :)

**Comment by typytypytypy** [comment]
@dglsparsons yes, this can be closed.  The issue was as you described, the first deployment pushes to production and preview, which was a behavior I was not expecting. Thank you for the insight!
