### ISSUE TITLE
Allow setting SSO and password protection

### ISSUE THREAD

**Issue by esanchezm** [vercel/terraform-provider-vercel#86]
There's no way to set up SSO or password protection at this moment, which would be quite helpful because that's something I have to change manually.

Is there any chance you can add it?

![image](https://user-images.githubusercontent.com/219745/201156487-cf799185-1646-41ac-b678-f09047b202a3.png)

![image](https://user-images.githubusercontent.com/219745/201156551-e29eea58-b605-4778-a511-84f96d6d00e6.png)

**Comment by dglsparsons** [comment]
Hey, thanks for raising this. It's a great suggestion! When I find time I'll look at getting it added :)

**Comment by dglsparsons** [comment]
Hi @esanchezm, Vercel Authentication (SSO Protection) and Password Protection are now available in the latest version of the provider (v0.13.0)[https://github.com/vercel/terraform-provider-vercel/releases/tag/v0.13.0].

The docs are [here](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project#nested-schema-for-password_protection). 

Please let me know if you encounter any issues! 🙌
