### ISSUE TITLE
[bug] The vercel_project data source returns an error

### ISSUE THREAD

**Issue by kenske** [vercel/terraform-provider-vercel#88]
Related to https://github.com/vercel/terraform-provider-vercel/issues/85

The `vercel_project` data source returns an error in `0.11.1`:

```
│ Error: Value Conversion Error
│ 
│   on line 1, in data "vercel_project" "example":
│    1: data "vercel_project" "example" {
│ 
│ An unexpected error was encountered trying to convert from struct value. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ couldn't find type information for attribute in supplied attr.Type types.ObjectType
```

This is what the data source looks like:

```
data "vercel_project" "example" {
  name    = "example"
  team_id = var.vercel_team_id
}
```

My provider config:

```
# API token is set in the VERCEL_API_TOKEN environment variable
provider "vercel" {
  team = local.vercel_team_id
}

```

I tested this with `0.10.3` and it works fine.

**Comment by dglsparsons** [comment]
Hey, sorry for this one - looks like I missed making some changes in the data source (only made them in the resource, but the model is shared). 

I've updated this, and it should be deployed shortly in v0.11.2. 

Please let me know if the issue remains on the latest version! 🙌

**Comment by kenske** [comment]
@dglsparsons it works! thanks for the quick turnaround
