### ISSUE TITLE
[Feature Request] export property to configure Node js version on project

### ISSUE THREAD

**Issue by andreyluchianic** [vercel/terraform-provider-vercel#97]
Vercel admin pannel has this option:
<img width="1377" alt="Screenshot 2023-01-10 at 11 42 43" src="https://user-images.githubusercontent.com/88837148/211516696-538aa11d-a637-4d08-a49f-3c8c2ec30217.png">

project settings: https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/deployment#nested-schema-for-project_settings

**Comment by dglsparsons** [comment]
Hi! 

This one is deliberately omitted, as it's possible control via a `package.json` `engines` field. 

Specifically: 
> Defining the node property inside [engines](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) of a package.json file will override the selection made in the Project Settings and print a Build Step warning if the version does not match. Please avoid greater than ranges, such as >14.x or >=14, because this will match semver major versions of Node.js once available which contains breaking changes.

From [here](https://vercel.com/docs/runtimes#official-runtimes/how-do-i-return-an-error/node-js-version).

**Comment by andreyluchianic** [comment]
oh great, thanks for help @dglsparsons 
i'm closing it
