### ISSUE TITLE
Should retry on rate limit

### ISSUE THREAD

**Issue by esanchezm** [vercel/terraform-provider-vercel#99]
Hello,

We have a set of projects with a bunch of environment variables. When our CD launches a terraform plan in all our projects we hit a rate limit in the Vercel API. I think it should retry to avoid failures as hitting a rate limit is something totally avoidable. I suggest implementing an exponential retry with a big limit.

This is especially frustrating, considering we fail for milliseconds.

```
│ Could not get project environment variable REDACTED
│ prj_REDACTED team_REDACTED unexpected
│ error: rate_limited - Too many requests - try again in -70 ms (more than
│ 120, code: "api-projects").
```

**Comment by esanchezm** [comment]
I'm sorry I can't give you any example as all the code is private. However, something that manages a big number of variables should work...

```hcl
locals {
  project_id = "SET_YOUR_PROJECT_ID_HERE"
  vars       = range(200)
}

resource "vercel_project_environment_variable" "var" {
  count = length(local.vars)

  project_id = local.project_id
  key        = format("VAR_%d", count.index)
  value      = "dummy"
  target     = ["production", "preview", "development"]
}
```

Haven't tested it and I reckon is ugly code, sorry 😅  If you can't make it to fail, try running many of this in parallel with different `project_id` values

**Comment by lucleray** [comment]
Hi all! Just a note that we've adjusted and improved Vercel's rate limits, which should _mostly_ prevent this issue from happening. More specifically, we've split the rate limit into more granular ones, and we've bumped the _Project environment variable retrieval per minute_ to 500/minute ([see docs](https://vercel.com/docs/concepts/limits/overview#rate-limits:~:text=Project%20environment%20variable%20retrieval%20per%20minute.)).

**Comment by dglsparsons** [comment]
I've added this behaviour in [v0.14.0](https://github.com/vercel/terraform-provider-vercel/releases/tag/v0.14.0)
